# Generated by Django 5.1.5 on 2025-01-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
